trigger:
 branches:
   include:
     - master


# pool:
#   name: personal-vm
pool:
  vmImage: 'ubuntu-latest'


stages:

# BUILD STAGE
- stage: Build
  displayName: 'Build Stage'
  jobs:
    - job: BuildandPush
      displayName: 'Build Job'
      steps:
        - task: AzureKeyVault@2
          inputs:
            azureSubscription: '$(ServiceConnectionName)'
            KeyVaultName: '$(keyVaultName)'
            SecretsFilter: '$(SecretName)'
            RunAsPreJob: true

        - task: Docker@2
          inputs:
            containerRegistry: '$(ACR-Service-Connection)'
            command: 'login'

        - task: Docker@2
          inputs:
            containerRegistry: '$(ACR-Service-Connection)'
            repository: '$(ImageName)'
            command: 'buildAndPush'
            Dockerfile: 'Dockerfile'
            buildContext: '$(Build.SourcesDirectory)'
            tags: |
             $(Build.BuildId)
          env:
           PORT: $(SecretName)
          
        - script: |
            python3.10 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
          displayName: 'Install dependencies'

    
- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
    - job: Test
      displayName: 'Dependencies'
      steps:
        - script: |
            python3.10 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
          displayName: 'Run Tests'

# DEPLOY STAGE
- stage: DeployDev
  displayName: 'DeployToDev'
  dependsOn: Test
  condition: succeeded()
  jobs:
    - job: Deploy
      displayName: 'Deploy to Azure'
    - deployment: deployDevJob
      environment: Dev
      strategy:
       runOnce:
         deploy:
           steps:
             - task: AzureWebAppContainer@1
               inputs:
                 azureSubscription: '$(ServiceConnectionName)'
                 appName: '$(appService-dev-new)'
                 containers: '$(AcrName).azurecr.io/$(ImageName):$(Build.BuildId)'

- stage: DeployProd
  displayName: 'DeployToProd'
  dependsOn: DeployDev
  condition: succeeded()
  jobs:
    - deployment: DeployProdJob
      environment: prod
      strategy: 
        runOnce:
          deploy:
            steps:
            
             - task: AzureWebAppContainer@1
               inputs:
                 azureSubscription: '$(ServiceConnectionName)'
                 appName: '$(appservice-prod)'
                 containers: '$(ImageName)'
  
      
    
      #  - task: AzureWebApp@1
       #   inputs:
        #    azureSubscription: 'DevOps-AppMod'
         #   appType: 'webAppLinux'
          #  appName: 'flask-cicd'
           # package: '$(Pipeline.Workspace)/drop/app.zip'
           # runtimeStack: 'PYTHON|3.11'
          #displayName: 'Deploy to Azure App Service'
