trigger:
- uat

pool:
  name: Default

variables:
  pythonVersion: '3.11'

stages:

- stage: Build
  displayName: 'Build Stage'
  jobs:
    - job: Build
      displayName: 'Build Job'
      steps:

        - script: |
            python3.11 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
          displayName: 'Create venv & install dependencies'

        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
            replaceExistingArchive: true
          displayName: 'Archive application'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
          displayName: 'Publish Build Artifacts'

- stage: Deploy
  displayName: 'Deploy Stage'
  jobs:
    - job: Deploy
      displayName: 'Deploy to Azure'
      steps:
        - download: current
          artifact: drop

        - task: AzureWebApp@1
          inputs:
            azureSubscription: 'DevOps-AppMod'
            appType: 'webAppLinux'
            appName: 'flask-cicd'
            package: '$(Pipeline.Workspace)/drop/app.zip'
            runtimeStack: 'PYTHON|3.11'
          displayName: 'Deploy to Azure App Service'
